### ISSUE TITLE
Shortcodes break rest of HTML in Micro.blog page

### ISSUE THREAD

**Issue by cygnoir** [jsonbecker/plugin-bookshop#1]
Hi! I have been trying to use the Bookshop shortcodes in my "Now" page on Micro.blog, but when I do, everything after the shortcode in the page is broken until the footer, which seems untouched.

Inspecting the page source, I see that there is an errant `</p>` after the `<script>` that the shortcode is entering. Could that be it?

**Comment by jsonbecker** [comment]
Can you post a link to your Now page and also paste the exact markdown of that page here?

**Comment by cygnoir** [comment]
I converted my Now page to Markdown from HTML and now the shortcode works.
