### ISSUE TITLE
Support stores and lists.

### ISSUE THREAD

**Issue by rkingett** [jsonbecker/plugin-bookshop#2]
Bookshop also has affiliate stores, as well as lists and search widgets. It would be epic if we could find a way to support these affiliate stores, wish lists, and other lists and the search widgets as well so people could make pages that contain bookstores from their affiliate accounts.

For an example of this list code, see the below.

              `<script
              src="https://bookshop.org/widgets.js"
              data-type="list" 
              data-list-slug="favorite-disability-fiction"></script>`

**Comment by jsonbecker** [comment]
I can't find any support for how to do the search widgets, but I'm going to add lists as a separate short code here.
